from collections import OrderedDict



# Define the ordered dictionary with the items
item_dict = OrderedDict([
    ('Single Gang Mud Ring', 0),
    ('Two Gang Mud Ring', 0),
    ('4-Square Bracket Box', 0),
    ('Deep 4-Square Bracket Box', 0),
    ('4-Square Box', 0),
    ('Deep 4-Square Box', 0),
    ('4-Square Cover', 0),
    ('Cut-In Box', 0),
    ('Drywall Clamps', 0),
    ('NVent Caddy Mounting Slider Bracket', 0),
    ('12/2 LV MC', 0),
    ('12/3 LV MC', 0),
    ('12/2 HV MC', 0),
    ('12/3 HV MC', 0),
    ('10/2 HV MC', 0),
    ('8/3 LV MC', 0),
    ('18/2 LV Dimmer Cable', 0),
    ('Single Barrel MC Connector', 0),
    ('Double Barrel MC Connector', 0),
    ('Ground Stinger', 0),
    ('Tek Screws', 0),
    ('1/2" Panhead Selftapper', 0),
    ('Mac-2 Straps', 0),
    ('Red Heads', 0),
    ('Red/Yellow Wire Nuts', 0),
    ('Blue/Orange Wire Nuts', 0),
    ('Big Blue Wire Nuts', 0),
    ('Jet Line', 0),
    ('3/4” Snap-In Bushings', 0),
    ('1" Snap-In Bushings', 0),
    ('Single Gang LV1s', 0),
    ('10ft Pieces of 2" EMT **May need adjusting per floor device specs**', 0),
    ('2" EMT Coupling **May need adjusting per floor device specs**', 0),
    ('2" EMT to Flex Change Over **May need adjusting per floor device specs**', 0),
    ('2" 90° Elbow **May need adjusting per floor device specs**', 0),
    ('10ft Pieces of 2" Flex **May need adjusting per floor device specs**', 0),
    ('2" Insulating Push On Conduit Bushing **May need adjusting per floor device specs**', 0),
    ('2" Min Strap **May need adjusting per floor device specs**', 0),
    ('Tube of Fire Cock **May need adjusting per floor device specs**', 0),
    ('1/4” Toggle Bolts', 0),
    ('1/2" EMT', 0),
    ('1/2" EMT Connectors', 0),
    ('1/2" One Hole Strap', 0),
    ('#12 THHN Black Wire', 0),
    ('#12 THHN White Wire', 0),
    ('#12 THHN Green Wire', 0),
    ('Standard Outlet', 0),
    ('Decora Outlet', 0),
    ('GFCI Outlet', 0),
    ('Half-Duplex Controlled Standard Outlet', 0),
    ('Half-Duplex Controlled Decora Outlet', 0),
    ('Full-Duplex Controlled Standard Outlet', 0),
    ('Full-Duplex Controlled Decora Outlet', 0),
    ('Single-Pole Motor Rated 30A Switch', 0),
    ('Two-Pole Motor Rated 40A Switch', 0),
    ('Single Gang Standard Outlet Cover Plate', 0),
    ('Single Gang Decora Outlet Cover Plate', 0),
    ('Two Gang Standard Outlet Cover Plate', 0),
    ('Two Gang Decora Outlet Cover Plate', 0),
    ('4-Square Industrial Switch Cover Plate', 0),
    ('Single Gang Standard Industrial Cover Plug Plate', 0),
    ('Single Gang Decora Industrial Cover Plug Plate', 0),
    ('2 Gang Standard Industrial Cover Plug Plate', 0),
    ('2 Gang Decora Industrial Cover Plug Plate', 0),
    ('3/4" MC Connector', 0),
    ('Two Gang Stainless Steel Blank Plate', 0),
    ('90 Degree 1/2" Flex Connector', 0),
    ('4" Floor Device ***Per Print***', 0),
    ('6" Floor Device ***Per Print***', 0),
    ('Floor Device to Flex Converter ***Per Print***', 0),
    ('Multifunction Clip w/ nut or bolt', 0),
    ('KX Straps', 0),
    ('Ceiling Wires', 0),
])
